#!/bin/sh
HERE=`dirname \`readlink -f $0\``
CORE=""
[ "$1" = "--core" ] && LL_SBCL_RUNTIME_FLAGS=("--core" "$2" "${LL_SBCL_RUNTIME_FLAGS[@]}") && shift 2
exec sbcl "${LL_SBCL_RUNTIME_FLAGS[@]}" --script "$HERE/system-loader.lisp" "${LOAD_LISP_FLAGS[@]}" "$@"
