#!/bin/sh
HERE=`dirname \`readlink -f $0\``
[ "$1" = "--core" ] && CORE="--core $2" && shift 2
sbcl $CORE $LL_SBCL_RUNTIME_FLAGS --noinform --no-userinit --load $HERE/system-loader.lisp $LOAD_LISP_FLAGS "$@"
